services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      args:
        VITE_BACKEND_PORT: ${BACKEND_PORT}
        VITE_BACKEND_ADMIN_EMAIL: ${BACKEND_ADMIN_EMAIL}
        VITE_BACKEND_ADMIN_PASSWORD: ${BACKEND_ADMIN_PASSWORD}
        VITE_FRONTEND_PORT: ${FRONTEND_PORT}
        VITE_FRONTEND_HMR_HOST: ${FRONTEND_HMR_HOST}
    container_name: frontend
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT}:80"
    volumes:
      - ./frontend:/frontend:cached
    env_file:
      - .env
    networks:
      - web_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      interval: 60s
      timeout: 20s
      retries: 5
      start_period: 10s
    depends_on:
      backend:
        condition: service_healthy
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend
    restart: unless-stopped
    ports:
      - "${BACKEND_PORT}:8090"
    volumes:
      - ./backend/pb_data:/pb_data
      - ./backend/pb_public:/pb_public
      - ./backend/pb_migrations:/pb_migrations
      - ./backend/pb_hooks:/pb_hooks
    env_file:
      - .env
    networks:
      - web_network
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 60s
      timeout: 20s
      retries: 5
      start_period: 10s
    entrypoint: ["/entrypoint.with-fixtures.sh"]

networks:
  web_network:
    name: web_network
    driver: bridge
