services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: unless-stopped
    ports:
      - "${VITE_FRONTEND_PORT:-5173}:80"
    volumes:
      - ./frontend/config:/config
      - ./frontend/data:/data
    env_file:
      - .env
    networks:
      - web_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      interval: 60s
      timeout: 20s
      retries: 5
      start_period: 10s
    depends_on:
      backend:
        condition: service_healthy
  backend:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: backend
    restart: unless-stopped
    ports:
      - "${BACKEND_PORT}:8090"
    volumes:
      - ./backend/pb_data:/pb_data
      - ./backend/pb_public:/pb_public
      - ./backend/pb_migrations:/pb_migrations
      - ./backend/pb_hooks:/pb_hooks
      - ./backend/entrypoint.sh:/entrypoint.sh
    env_file:
      - .env
    networks:
      - web_network
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 60s
      timeout: 20s
      retries: 5
      start_period: 10s
    entrypoint: ["/entrypoint.sh"]

networks:
  web_network:
    name: web_network
    driver: bridge
